name: dressing_both_arms_real_lowdim

obs_dim: 16
action_dim: 2
keypoint_dim: 0
obs_eef_target: False

dataset:
  _target_: diffusion_policy.dataset.dressing_real_lowdim_dataset.DressingRealLowdimDataset
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  obs_eef_target: ${task.obs_eef_target}
  use_manual_normalizer: False
  seed: 42
  val_ratio: 0.0
  num_datasets: 3
  include_datasets: ["sim", "real_first_arm", "real_second_arm"]
  zarr_configs:
  - path: /scratch/pnt8/first_arm_scene/datasets/halton_base_dagger_rd2_x3_upsampled_x4.zarr
    name: sim
    max_train_episodes: 360
    sampling_weight: 0.1
    val_ratio: 0.1 
    upsampled: True
    upsample_multiplier: 4
  - path: None      # TODO : insert
    name: real_first_arm
    max_train_episodes: 18
    sampling_weight: 1.0
    val_ratio: 0.1 # 2 / 20 trajectories
    upsampled: True
    upsample_multiplier: 2
  - path: None
    name: real_second_arm
    max_train_episodes: 18
    sampling_weight: 1.0
    val_ratio: 0.1 # 2 / 20 trajectories
    upsampled: True
    upsample_multiplier: 2


