name: first_arm_env_lowdim

obs_dim: 16
action_dim: 2
keypoint_dim: 0
obs_eef_target: False

dataset:
  _target_: diffusion_policy.dataset.first_arm_lowdim_dataset.FirstArmLowdimDataset
  zarr_path: /home/pranavnnt/workspace/dressing_sim_ws/dressing_policies/demos/halton_base_dagger_rd1_x3.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  obs_eef_target: ${task.obs_eef_target}
  use_manual_normalizer: False
  seed: 42
  val_ratio: 0.02
  upsampled: True
  upsample_multiplier: 5 
  eval: True
